services:
  client:
    build: ./CLIENT
    ports:
      - "3001:80" # Changed to avoid conflict
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./SERVER
    ports:
      - "3000:3000" # Kept the same
    env_file: .env
    environment:
      NODE_ENV: development
      DB_URL: ${DB_URL}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
